name: CI

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-
      - run: |
          npm ci
          node index.js
      - name: Commit report
        run: |
          git config --global user.name 'school55'
          git config --global user.email 'kzh55@ukr.net'          
          git commit -am "Automated report"
          git push
